---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[rtorrent::default]
  attributes:
    rtorrent:
      btsync: true
      btsync_dir: '.sync'
